apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel-container
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPO_NAME }}:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "YOUR_RDS_ENDPOINT"
            - name: DB_DATABASE
              value: "laravel_db"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD
              value: "Gajen@97"
